2025-07-14T07:31:22Z info: Deployment: 10febe7c-0c50-4ce3-8dfb-22896c560dc1
2025-07-14T07:31:22Z info: Build: 91b90d4f-67ea-40ad-8aeb-49db57f74592
2025-07-14T07:31:22Z info: Connecting to builder
2025-07-14T07:31:24Z info: Builder connected
2025-07-14T07:31:26Z info: Installing packages
--> pip install -r requirements.txt

Requirement already satisfied: psycopg2-binary in ./.pythonlibs/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.9.10)

Requirement already satisfied: flask_sqlalchemy in ./.pythonlibs/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (3.1.1)
Requirement already satisfied: openai in ./.pythonlibs/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.95.1)
Requirement already satisfied: flask_login in ./.pythonlibs/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.6.3)

Requirement already satisfied: requests in ./.pythonlibs/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (2.32.4)

Requirement already satisfied: flask>=2.2.5 in ./.pythonlibs/lib/python3.11/site-packages (from flask_sqlalchemy->-r requirements.txt (line 2)) (3.1.1)

Requirement already satisfied: sqlalchemy>=2.0.16 in ./.pythonlibs/lib/python3.11/site-packages (from flask_sqlalchemy->-r requirements.txt (line 2)) (2.0.41)

Requirement already satisfied: anyio<5,>=3.5.0 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (1.9.0)

Requirement already satisfied: httpx<1,>=0.23.0 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (0.28.1)

Requirement already satisfied: jiter<1,>=0.4.0 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (0.10.0)

Requirement already satisfied: pydantic<3,>=1.9.0 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (2.11.7)

Requirement already satisfied: sniffio in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (1.3.1)

Requirement already satisfied: tqdm>4 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (4.67.1)

Requirement already satisfied: typing-extensions<5,>=4.11 in ./.pythonlibs/lib/python3.11/site-packages (from openai->-r requirements.txt (line 3)) (4.14.1)

Requirement already satisfied: Werkzeug>=1.0.1 in ./.pythonlibs/lib/python3.11/site-packages (from flask_login->-r requirements.txt (line 4)) (3.1.3)

Requirement already satisfied: charset_normalizer<4,>=2 in ./.pythonlibs/lib/python3.11/site-packages (from requests->-r requirements.txt (line 5)) (3.4.2)

Requirement already satisfied: idna<4,>=2.5 in ./.pythonlibs/lib/python3.11/site-packages (from requests->-r requirements.txt (line 5)) (3.10)

Requirement already satisfied: urllib3<3,>=1.21.1 in ./.pythonlibs/lib/python3.11/site-packages (from requests->-r requirements.txt (line 5)) (2.5.0)

Requirement already satisfied: certifi>=2017.4.17 in ./.pythonlibs/lib/python3.11/site-packages (from requests->-r requirements.txt (line 5)) (2025.7.14)

Requirement already satisfied: blinker>=1.9.0 in ./.pythonlibs/lib/python3.11/site-packages (from flask>=2.2.5->flask_sqlalchemy->-r requirements.txt (line 2)) (1.9.0)

Requirement already satisfied: click>=8.1.3 in ./.pythonlibs/lib/python3.11/site-packages (from flask>=2.2.5->flask_sqlalchemy->-r requirements.txt (line 2)) (8.2.1)

Requirement already satisfied: itsdangerous>=2.2.0 in ./.pythonlibs/lib/python3.11/site-packages (from flask>=2.2.5->flask_sqlalchemy->-r requirements.txt (line 2)) (2.2.0)

Requirement already satisfied: jinja2>=3.1.2 in ./.pythonlibs/lib/python3.11/site-packages (from flask>=2.2.5->flask_sqlalchemy->-r requirements.txt (line 2)) (3.1.6)

Requirement already satisfied: markupsafe>=2.1.1 in ./.pythonlibs/lib/python3.11/site-packages (from flask>=2.2.5->flask_sqlalchemy->-r requirements.txt (line 2)) (3.0.2)

Requirement already satisfied: httpcore==1.* in ./.pythonlibs/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai->-r requirements.txt (line 3)) (1.0.9)

Requirement already satisfied: h11>=0.16 in ./.pythonlibs/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->-r requirements.txt (line 3)) (0.16.0)

Requirement already satisfied: annotated-types>=0.6.0 in ./.pythonlibs/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 3)) (0.7.0)

Requirement already satisfied: pydantic-core==2.33.2 in ./.pythonlibs/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 3)) (2.33.2)

Requirement already satisfied: typing-inspection>=0.4.0 in ./.pythonlibs/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai->-r requirements.txt (line 3)) (0.4.1)

Requirement already satisfied: greenlet>=1 in ./.pythonlibs/lib/python3.11/site-packages (from sqlalchemy>=2.0.16->flask_sqlalchemy->-r requirements.txt (line 2)) (3.2.3)

2025-07-14T07:31:31Z info: Skipping Build as no Build command set
2025-07-14T07:31:32Z info: Pushing pid1 binary layer...
2025-07-14T07:31:36Z info: Pushing hosting layer...
2025-07-14T07:31:36Z info: Pushing Repl layer...
2025-07-14T07:31:36Z info: Retrieved cached nix layer
2025-07-14T07:31:37Z info: Created hosting layer
2025-07-14T07:31:41Z info: Created pid1 binary layer
2025-07-14T07:32:09Z info: Created Repl layer
2025-07-14T07:32:09Z info: Pushing Repl (cache) layer...
2025-07-14T07:32:10Z info: Created Repl (cache) layer
2025-07-14T07:32:11Z info: Pushed image manifest
2025-07-14T07:32:13Z info: Pushed soci index manifest
2025-07-14T07:32:17Z info: Creating Autoscale service
forwarding local port 5000 to external port 80 (mapped as 1104)
starting up user application
command finished with error [sh -c python -m main.py]: exit status 1
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
/home/runner/workspace/.pythonlibs/bin/python: Error while finding module specification for 'main.py' (ModuleNotFoundError: __path__ attribute not found on 'main' while trying to find 'main.py'). Try using 'main' instead of 'main.py' as the module name.
command finished with error [sh -c python -m main.py]: exit status 1
crash loop detected
2025-07-14T07:34:07Z error: The deployment is crash looping. This can happen if the run command fails or exits immediately after starting. Check the logs for more information.